// <auto-generated />
using DmitriyVanchinKt_42_21.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DmitriyVanchinKt_42_21.Migrations
{
    [DbContext(typeof(LecturerDbContext))]
    partial class LecturerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DmitriyVanchinKt_42_21.Models.Cathedra", b =>
                {
                    b.Property<int>("CathedraId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cathedra_id")
                        .HasComment("Идентификатор записи кафедры");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CathedraId"));

                    b.Property<string>("CathedraName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_cathedra_name")
                        .HasComment("Название кафедры");

                    b.Property<int>("HeadLecturerId")
                        .HasColumnType("integer")
                        .HasColumnName("head_lecturer_id")
                        .HasComment("Идентификатор заведующего кафедрой");

                    b.HasKey("CathedraId")
                        .HasName("pk_cd_cathedra_cathedra_id");

                    b.HasIndex("HeadLecturerId")
                        .IsUnique();

                    b.ToTable("cd_cathedra", (string)null);
                });

            modelBuilder.Entity("DmitriyVanchinKt_42_21.Models.Discipline", b =>
                {
                    b.Property<int>("DisciplineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("discipline_id")
                        .HasComment("Идентификатор записи дисциплины");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DisciplineId"));

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_discipline_name")
                        .HasComment("Название дисциплины");

                    b.HasKey("DisciplineId")
                        .HasName("pk_cd_discipline_discipline_id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("DmitriyVanchinKt_42_21.Models.Lecturer", b =>
                {
                    b.Property<int>("LecturerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("lecturer_id")
                        .HasComment("Идентификатор записи предподавателя");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LecturerId"));

                    b.Property<int>("CathedraId")
                        .HasColumnType("integer");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_lecturer_firstname")
                        .HasComment("Имя предподавателя");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_lecturer_lactname")
                        .HasComment("Фамилия предподавателя");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar")
                        .HasColumnName("c_lecturer_middlename")
                        .HasComment("Отчество предподавателя");

                    b.HasKey("LecturerId")
                        .HasName("pk_cd_lecturer_lecturer_id");

                    b.HasIndex(new[] { "CathedraId" }, "idx_cd_lecturer_fk_f_cathedra_id");

                    b.ToTable("cd_lecturer", (string)null);
                });

            modelBuilder.Entity("DmitriyVanchinKt_42_21.Models.Load", b =>
                {
                    b.Property<int>("LoadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LoadId"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("LecturerId")
                        .HasColumnType("integer");

                    b.Property<int>("OpeningHours")
                        .HasColumnType("integer");

                    b.HasKey("LoadId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("LecturerId");

                    b.ToTable("Loads");
                });

            modelBuilder.Entity("DmitriyVanchinKt_42_21.Models.Cathedra", b =>
                {
                    b.HasOne("DmitriyVanchinKt_42_21.Models.Lecturer", "HeadLecturer")
                        .WithOne()
                        .HasForeignKey("DmitriyVanchinKt_42_21.Models.Cathedra", "HeadLecturerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cathedra_head_lecturer_id");

                    b.Navigation("HeadLecturer");
                });

            modelBuilder.Entity("DmitriyVanchinKt_42_21.Models.Lecturer", b =>
                {
                    b.HasOne("DmitriyVanchinKt_42_21.Models.Cathedra", "Cathedra")
                        .WithMany()
                        .HasForeignKey("CathedraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_f_cathedra_id");

                    b.Navigation("Cathedra");
                });

            modelBuilder.Entity("DmitriyVanchinKt_42_21.Models.Load", b =>
                {
                    b.HasOne("DmitriyVanchinKt_42_21.Models.Discipline", "Discipline")
                        .WithMany()
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DmitriyVanchinKt_42_21.Models.Lecturer", "Lecturer")
                        .WithMany()
                        .HasForeignKey("LecturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Lecturer");
                });
#pragma warning restore 612, 618
        }
    }
}
